### PR TITLE
API proposal

### PR DESCRIPTION
**Pull request by aswan**

### CODE REVIEW

**Comment by aswan** [comment]
@mixedpuppy I've separated the conversion from the google doc and the subsequent edits into separate commits, hopefully that makes reviewing this easier.

**Comment by mixedpuppy** [comment]
This is not a strong opinion.  

On permissions, do we have addons that only use nsiloginmanager to manage a single or subset of logins?  If not (or not significant), I'd be inclined to keep it simple and just have a logins permission access the full db.  It could be refined further if necessary based on feedback from developers using it (or if we discover via addon analysis that the use case would be common).

**Comment by aswan** [comment]
> do we have addons that only use nsiloginmanager to manage a single or subset of logins?

I think by far the most common use is for extensions that store their own credentials in the login manager (which perhaps we should just allow by default without even an explicit "logins" permission?).  Another case is extensions that want to issue requests to some site and do so transparently if there are saved credentials for the site -- restricting what is visible to the extension in that case seems compelling to me.

**Comment by mixedpuppy** [comment]
Yeah, I thought about no permission for addons storing their own credentials.  I think the benefit could be one less prompt for the user, but I'm not certain that will end up being reality, depends on the permissions design.  I am probably overspinning on this, it's an experiment and we can get feedback from devs during the process.

**Pull request merged**
